version: "3"

services:
    api:
      build: .
      ports:
        - "8080:8080"
      volumes:
        - ./api:/api
      working_dir: /api
      command: php -S 0.0.0.0:8080 -t public
      networks:
        - app-network

    mysql-app:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      ports:
        - "3306:3306"
      volumes:
        - .docker/dbdata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: papibaquigrafo
        MYSQL_ROOT_PASSWORD: papibaquigrafo
        MYSQL_USER: papibaquigrafo
        MYSQL_PASSWORD: papibaquigrafo
      networks:
          - app-network

networks:
  app-network:
    driver: bridge
